# Generated by Django 5.2.4 on 2026-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cohort',
            field=models.CharField(blank=True, choices=[('cohort 1', 'Cohort 1'), ('cohort 2', 'Cohort 2'), ('cohort 3', 'Cohort 3'), ('cohort 4', 'Cohort 4')], help_text='e.g. Cohort 1, Batch A', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
