# Generated by Django 5.0 on 2026-05-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_applicant_cohort_alter_applicant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Time the session ends', null=True),
        ),
    ]
