# Generated by Django 5.0 on 2026-05-19 12:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_session_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AddField(
            model_name='session',
            name='checkin_code',
            field=models.CharField(default=core.models._generate_checkin_code, help_text='6-character code printed and posted at the centre for manual check-in', max_length=6),
        ),
    ]
