# Generated by Django 5.2.4 on 2026-05-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_session_options_session_checkin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
